[build]
  command = "npm run build"
  publish = ".next"
  functions = ".netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/_ipx/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  